### ISSUE TITLE
Linea 106 de arbol.py

### ISSUE THREAD

**Issue by flynn1411** [isaacrivas10/arbol-proyecto-aed#1]
La consola me da ese error al querer llamar la función getBranches para correr "pwd":
![screen1](https://user-images.githubusercontent.com/41033043/53615516-daea3180-3ba3-11e9-822c-e402f4dab587.png)
Aquí está esa linea de codigo:
![screenshot from 2019-02-28 21-58-22](https://user-images.githubusercontent.com/41033043/53615545-053bef00-3ba4-11e9-99c2-080fc78fa9c5.png)

**Comment by isaacrivas10** [comment]
Ya está corregido, solamente toma encuenta ahora que los nodos ya no tienen el atributo de Lista Enlazada, solamente las carpetas. Asi que si queres trabajar con un nodo, y sabes que este nodo contiene una carpeta, debes trabajar con su valor, osea la instancia de Carpeta y esta si tiene Lista Enlazada.
